# hostname (and path) to the root
baseURL: "https://vanillajstoolkit.com"

# Customer parameters
params:
  description: "A growing collection of vanilla JavaScript code snippets, helper functions, polyfills, plugins, and learning resources."
  rssURL: ""
  rssLimit: 7
  cacheBust: true
  version: "1.2.2"

# The language code for the site
languageCode: "en-us"

# Site title
title: "The Vanilla JS Toolkit"

# theme to use (located by default in /themes/THEMENAME/)
theme: "vanillajs"

# Permalinks
# See "content-management/permalinks"
permalinks:
  articles: /:title/

# Allows you to disable all page types and will render nothing related to 'kind';
# values = "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"
disableKinds: ["RSS", "hugoGeneratorInject", "404"]

# Files to ignore while rendering
ignoreFiles: []

# the length of text to show in a .Summary
summaryLength: 70

# Pagination
paginate: 35
paginatePath: "page"

# Markdown Options
blackfriday:
  fractions: false

# Site taxonomies
taxonomies:
  - category: "categories"
  - tag: "tags"